name: core
description: Core package containing network, DI, storage, and utilities
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.8.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter

  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0

  # HTTP Client
  dio: ^5.9.0

  # Local Storage
  shared_preferences: ^2.3.3

  # JSON Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

  # Navigation & Routing
  go_router: ^16.3.0

  # Utils
  equatable: ^2.0.7
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^3.1.0
  injectable_generator: ^2.6.2

